- src/app/chat/chat-widget/chat-widget.component.html
- src/app/chat/chat-widget/chat-widget.component.ts
- src/app/libs/constant/hello-widget-integration.ts
- src/index.html
https://app.clickup.com/t/86cxmqp2t
> H2290 | chat icon number values check add console

- src/app/chat/chat-widget/components/artible-pop/article-popup.component.scss
https://app.clickup.com/t/86cxnaz3b
> O0760 | T478951 | Push notification not displayed in correct format

- src/app/chat/chat-widget/components/selected-channel/selected-channel.component.html
https://app.clickup.com/t/86cxwvexx
> O0769 | Bug :- Content is not showing proper at widget

- src/app/chat/chat-widget/components/chat-view/chat-view.component.html
- src/app/chat/chat-widget/components/chat-view/chat-view.component.ts
https://app.clickup.com/t/86cxxupnh
> O0771 clean

- src/app/chat/chat-widget/components/chat-view/chat-view.component.ts
https://app.clickup.com/t/86cxxupnh
> O0771 | Bug

- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.html
- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.ts
https://app.clickup.com/t/86cxvf5kx
> O0764 test

- angular.json
- package.json
- src/app/chat/chat-widget/components/selected-channel/components/feedback-form/feedback-form.component.ts
- src/environments/environment.prod.ts
- src/environments/environment.stage.ts
- src/environments/environment.ts
https://app.clickup.com/t/86cy2zqvh
> O0775 | When client send the feedback by widget console gives an error 

- src/assets/scss/theme/_default-theme.scss
https://app.clickup.com/t/86cy4rak2
> import theme file

- angular.json
- src/assets/scss/theme/theme_theme-colors.scss
https://app.clickup.com/t/86cy4rak2
> revert file path changes

- src/app/chat/store/effects/widgetInfo/widget-info.effects.ts
https://app.clickup.com/t/86cy4pcah
> O0780 | Fixed bug: even if unique id exist anonymous client is showing in segmento

- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.html
- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.ts
> remove all code to esting code

- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.html
- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.ts
> testing code

- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.html
> testing purpes

- src/app/chat/store/effects/widgetInfo/widget-info.effects.ts
https://app.clickup.com/t/86cy4pcah
> O0781 | fixed bug: even if unique id exist anonymous client is showing in segmento

- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.html
- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.ts
https://app.clickup.com/t/86cxgdgx5
> O0779 | CSS is not rendering on Widget side

- src/app/chat/chat-widget/components/team-list/team-list.component.scss
https://app.clickup.com/t/86cyb4xvv
> O0785 | Adding teams in widget overlaps each other

- src/app/chat/chat-widget/components/faq-view/faq-view.component.scss
- src/app/chat/chat-widget/components/selected-channel/selected-channel.component.scss
- src/assets/scss/theme/theme_theme-colors.scss
- src/styles.scss
https://app.clickup.com/t/86cy4rak2
> O0785 | Chat Widget | Update Angular Version from 16 to 19

- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.html
- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.scss
- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.ts
- src/app/chat/model/message.ts
https://app.clickup.com/t/86cyfvphd
> H2393 | Getting link of the Hello meet on widget end instead of the button

- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.ts
Reverts Walkover-Web-Solution/chat-widget#116
> Revert "meet link issue on stage"

- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.ts
Reverts Walkover-Web-Solution/chat-widget#118
> Revert "remove video call condition"

- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.html
- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.ts
https://app.clickup.com/t/86cyfvphd
> H2393 | meet link not showing in button form in first time

- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.html
- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.ts
Reverts Walkover-Web-Solution/chat-widget#124
> Revert "H2393 | meet link not showing in button form in first time"

- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.ts
Reverts Walkover-Web-Solution/chat-widget#126
> Revert "H2393  | video call not working"

- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.html
- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.ts
Reverts Walkover-Web-Solution/chat-widget#128
> Revert "H2393 video link"

- src/app/chat/chat-widget/components/selected-channel/components/in-message/in-message.component.ts
Reverts Walkover-Web-Solution/chat-widget#131
> Revert "H2393 | ngon change video call"

- src/app/chat/chat-widget/chat-widget.component.ts
https://app.clickup.com/t/86cyq5fbp
> M0060 | For anonymous user channel are getting disappear on refresh
